/**
 * Mapeo exhaustivo de componentes React UI → PrimeNG.
 * Cubre MUI, Ant Design, Chakra UI, React Bootstrap y HTML nativo.
 */
import type { PrimeNgComponentMapping } from '../models/primeng-mapping.model.js';

export const PRIMENG_COMPONENT_MAP: Record<string, PrimeNgComponentMapping> = {
  // ─── Botones ──────────────────────────────────────────────────────────
  Button: {
    reactComponent: 'Button',
    primeNgComponent: 'Button',
    primeNgModule: 'ButtonModule',
    importPath: 'primeng/button',
    selector: 'p-button',
    templateExample: '<p-button label="{{label}}" [icon]="icon" (onClick)="handler()" severity="{{severity}}" />',
    requiredInputs: ['label'],
  },
  IconButton: {
    reactComponent: 'IconButton',
    primeNgComponent: 'Button',
    primeNgModule: 'ButtonModule',
    importPath: 'primeng/button',
    selector: 'p-button',
    templateExample: '<p-button [icon]="icon" [rounded]="true" [text]="true" (onClick)="handler()" />',
    requiredInputs: ['icon'],
  },
  Fab: {
    reactComponent: 'Fab',
    primeNgComponent: 'SpeedDial',
    primeNgModule: 'SpeedDialModule',
    importPath: 'primeng/speeddial',
    selector: 'p-speedDial',
    templateExample: '<p-speedDial [model]="items" />',
    requiredInputs: ['model'],
  },

  // ─── Inputs / Formularios ─────────────────────────────────────────────
  TextField: {
    reactComponent: 'TextField',
    primeNgComponent: 'InputText',
    primeNgModule: 'InputTextModule',
    importPath: 'primeng/inputtext',
    selector: 'input pInputText',
    templateExample: '<input pInputText [(ngModel)]="value" placeholder="{{placeholder}}" />',
    requiredInputs: [],
  },
  TextArea: {
    reactComponent: 'TextArea',
    primeNgComponent: 'InputTextarea',
    primeNgModule: 'InputTextareaModule',
    importPath: 'primeng/inputtextarea',
    selector: 'textarea pInputTextarea',
    templateExample: '<textarea pInputTextarea [(ngModel)]="value" [rows]="5"></textarea>',
    requiredInputs: [],
  },
  Select: {
    reactComponent: 'Select',
    primeNgComponent: 'Select',
    primeNgModule: 'SelectModule',
    importPath: 'primeng/select',
    selector: 'p-select',
    templateExample: '<p-select [options]="options" [(ngModel)]="selected" optionLabel="label" placeholder="Seleccione..." />',
    requiredInputs: ['options'],
  },
  MenuItem: {
    reactComponent: 'MenuItem',
    primeNgComponent: 'Select',
    primeNgModule: 'SelectModule',
    importPath: 'primeng/select',
    selector: 'p-select',
    templateExample: '<!-- MenuItem se integra como opción dentro de p-select -->',
    requiredInputs: [],
  },
  Checkbox: {
    reactComponent: 'Checkbox',
    primeNgComponent: 'Checkbox',
    primeNgModule: 'CheckboxModule',
    importPath: 'primeng/checkbox',
    selector: 'p-checkbox',
    templateExample: '<p-checkbox [(ngModel)]="checked" [binary]="true" label="{{label}}" />',
    requiredInputs: [],
  },
  Switch: {
    reactComponent: 'Switch',
    primeNgComponent: 'InputSwitch',
    primeNgModule: 'InputSwitchModule',
    importPath: 'primeng/inputswitch',
    selector: 'p-inputSwitch',
    templateExample: '<p-inputSwitch [(ngModel)]="checked" />',
    requiredInputs: [],
  },
  Radio: {
    reactComponent: 'Radio',
    primeNgComponent: 'RadioButton',
    primeNgModule: 'RadioButtonModule',
    importPath: 'primeng/radiobutton',
    selector: 'p-radioButton',
    templateExample: '<p-radioButton name="group" value="{{value}}" [(ngModel)]="selected" label="{{label}}" />',
    requiredInputs: ['name', 'value'],
  },
  Slider: {
    reactComponent: 'Slider',
    primeNgComponent: 'Slider',
    primeNgModule: 'SliderModule',
    importPath: 'primeng/slider',
    selector: 'p-slider',
    templateExample: '<p-slider [(ngModel)]="value" />',
    requiredInputs: [],
  },
  Autocomplete: {
    reactComponent: 'Autocomplete',
    primeNgComponent: 'AutoComplete',
    primeNgModule: 'AutoCompleteModule',
    importPath: 'primeng/autocomplete',
    selector: 'p-autoComplete',
    templateExample: '<p-autoComplete [(ngModel)]="value" [suggestions]="results" (completeMethod)="search($event)" />',
    requiredInputs: ['suggestions'],
  },
  DatePicker: {
    reactComponent: 'DatePicker',
    primeNgComponent: 'Calendar',
    primeNgModule: 'CalendarModule',
    importPath: 'primeng/calendar',
    selector: 'p-calendar',
    templateExample: '<p-calendar [(ngModel)]="date" dateFormat="dd/mm/yy" />',
    requiredInputs: [],
  },

  // ─── Data Display ───────────────────────────────────────────────────
  Table: {
    reactComponent: 'Table',
    primeNgComponent: 'Table',
    primeNgModule: 'TableModule',
    importPath: 'primeng/table',
    selector: 'p-table',
    templateExample: `<p-table [value]="items" [paginator]="true" [rows]="10" [showCurrentPageReport]="true"
  currentPageReportTemplate="Mostrando {first} a {last} de {totalRecords} registros"
  [rowsPerPageOptions]="[10, 25, 50]" styleClass="sb-table">
  <ng-template pTemplate="header">
    <tr>
      <th pSortableColumn="field">Columna <p-sortIcon field="field" /></th>
    </tr>
  </ng-template>
  <ng-template pTemplate="body" let-item>
    <tr>
      <td>{{ item.field }}</td>
    </tr>
  </ng-template>
</p-table>`,
    requiredInputs: ['value'],
  },
  DataGrid: {
    reactComponent: 'DataGrid',
    primeNgComponent: 'DataView',
    primeNgModule: 'DataViewModule',
    importPath: 'primeng/dataview',
    selector: 'p-dataView',
    templateExample: '<p-dataView [value]="items" layout="grid" />',
    requiredInputs: ['value'],
  },
  List: {
    reactComponent: 'List',
    primeNgComponent: 'Listbox',
    primeNgModule: 'ListboxModule',
    importPath: 'primeng/listbox',
    selector: 'p-listbox',
    templateExample: '<p-listbox [options]="items" [(ngModel)]="selected" optionLabel="label" />',
    requiredInputs: ['options'],
  },
  ListItem: {
    reactComponent: 'ListItem',
    primeNgComponent: 'Listbox',
    primeNgModule: 'ListboxModule',
    importPath: 'primeng/listbox',
    selector: 'p-listbox',
    templateExample: '<!-- ListItem se integra como opción dentro de p-listbox -->',
    requiredInputs: [],
  },
  TreeView: {
    reactComponent: 'TreeView',
    primeNgComponent: 'Tree',
    primeNgModule: 'TreeModule',
    importPath: 'primeng/tree',
    selector: 'p-tree',
    templateExample: '<p-tree [value]="nodes" selectionMode="single" [(selection)]="selectedNode" />',
    requiredInputs: ['value'],
  },
  Chip: {
    reactComponent: 'Chip',
    primeNgComponent: 'Chip',
    primeNgModule: 'ChipModule',
    importPath: 'primeng/chip',
    selector: 'p-chip',
    templateExample: '<p-chip label="{{label}}" [removable]="true" />',
    requiredInputs: ['label'],
  },
  Badge: {
    reactComponent: 'Badge',
    primeNgComponent: 'Badge',
    primeNgModule: 'BadgeModule',
    importPath: 'primeng/badge',
    selector: 'p-badge',
    templateExample: '<p-badge [value]="count" severity="{{severity}}" />',
    requiredInputs: ['value'],
  },
  Avatar: {
    reactComponent: 'Avatar',
    primeNgComponent: 'Avatar',
    primeNgModule: 'AvatarModule',
    importPath: 'primeng/avatar',
    selector: 'p-avatar',
    templateExample: '<p-avatar label="{{initials}}" shape="circle" size="large" styleClass="sb-avatar" />',
    requiredInputs: [],
  },
  Tag: {
    reactComponent: 'Tag',
    primeNgComponent: 'Tag',
    primeNgModule: 'TagModule',
    importPath: 'primeng/tag',
    selector: 'p-tag',
    templateExample: '<p-tag value="{{label}}" severity="{{severity}}" />',
    requiredInputs: ['value'],
  },
  Timeline: {
    reactComponent: 'Timeline',
    primeNgComponent: 'Timeline',
    primeNgModule: 'TimelineModule',
    importPath: 'primeng/timeline',
    selector: 'p-timeline',
    templateExample: '<p-timeline [value]="events" />',
    requiredInputs: ['value'],
  },

  // ─── Contenedores / Layout ────────────────────────────────────────────
  Card: {
    reactComponent: 'Card',
    primeNgComponent: 'Card',
    primeNgModule: 'CardModule',
    importPath: 'primeng/card',
    selector: 'p-card',
    templateExample: '<p-card header="{{title}}" subheader="{{subtitle}}" styleClass="sb-card">\n  <ng-template pTemplate="content">\n    <!-- contenido -->\n  </ng-template>\n</p-card>',
    requiredInputs: [],
  },
  CardContent: {
    reactComponent: 'CardContent',
    primeNgComponent: 'Card',
    primeNgModule: 'CardModule',
    importPath: 'primeng/card',
    selector: 'p-card',
    templateExample: '<!-- CardContent se integra como ng-template pTemplate="content" dentro de p-card -->',
    requiredInputs: [],
  },
  CardHeader: {
    reactComponent: 'CardHeader',
    primeNgComponent: 'Card',
    primeNgModule: 'CardModule',
    importPath: 'primeng/card',
    selector: 'p-card',
    templateExample: '<!-- CardHeader se mapea al atributo header de p-card -->',
    requiredInputs: [],
  },
  Accordion: {
    reactComponent: 'Accordion',
    primeNgComponent: 'Accordion',
    primeNgModule: 'AccordionModule',
    importPath: 'primeng/accordion',
    selector: 'p-accordion',
    templateExample: '<p-accordion>\n  <p-accordionTab header="{{title}}">\n    <!-- contenido -->\n  </p-accordionTab>\n</p-accordion>',
    requiredInputs: [],
  },
  Panel: {
    reactComponent: 'Panel',
    primeNgComponent: 'Panel',
    primeNgModule: 'PanelModule',
    importPath: 'primeng/panel',
    selector: 'p-panel',
    templateExample: '<p-panel header="{{title}}" [toggleable]="true" styleClass="sb-panel">\n  <!-- contenido -->\n</p-panel>',
    requiredInputs: [],
  },
  Divider: {
    reactComponent: 'Divider',
    primeNgComponent: 'Divider',
    primeNgModule: 'DividerModule',
    importPath: 'primeng/divider',
    selector: 'p-divider',
    templateExample: '<p-divider />',
    requiredInputs: [],
  },
  Fieldset: {
    reactComponent: 'Fieldset',
    primeNgComponent: 'Fieldset',
    primeNgModule: 'FieldsetModule',
    importPath: 'primeng/fieldset',
    selector: 'p-fieldset',
    templateExample: '<p-fieldset legend="{{title}}" [toggleable]="true">\n  <!-- contenido -->\n</p-fieldset>',
    requiredInputs: ['legend'],
  },

  // ─── Navegación ───────────────────────────────────────────────────────
  Tabs: {
    reactComponent: 'Tabs',
    primeNgComponent: 'TabView',
    primeNgModule: 'TabViewModule',
    importPath: 'primeng/tabview',
    selector: 'p-tabView',
    templateExample: '<p-tabView styleClass="sb-tabs">\n  <p-tabPanel header="{{title}}">\n    <!-- contenido -->\n  </p-tabPanel>\n</p-tabView>',
    requiredInputs: [],
  },
  Tab: {
    reactComponent: 'Tab',
    primeNgComponent: 'TabPanel',
    primeNgModule: 'TabViewModule',
    importPath: 'primeng/tabview',
    selector: 'p-tabPanel',
    templateExample: '<p-tabPanel header="{{title}}"><!-- contenido --></p-tabPanel>',
    requiredInputs: ['header'],
  },
  AppBar: {
    reactComponent: 'AppBar',
    primeNgComponent: 'Menubar',
    primeNgModule: 'MenubarModule',
    importPath: 'primeng/menubar',
    selector: 'p-menubar',
    templateExample: '<p-menubar [model]="menuItems" styleClass="sb-menubar" />',
    requiredInputs: ['model'],
  },
  Toolbar: {
    reactComponent: 'Toolbar',
    primeNgComponent: 'Toolbar',
    primeNgModule: 'ToolbarModule',
    importPath: 'primeng/toolbar',
    selector: 'p-toolbar',
    templateExample: '<p-toolbar styleClass="sb-toolbar">\n  <div class="p-toolbar-group-start"><!-- izquierda --></div>\n  <div class="p-toolbar-group-end"><!-- derecha --></div>\n</p-toolbar>',
    requiredInputs: [],
  },
  Drawer: {
    reactComponent: 'Drawer',
    primeNgComponent: 'Sidebar',
    primeNgModule: 'SidebarModule',
    importPath: 'primeng/sidebar',
    selector: 'p-sidebar',
    templateExample: '<p-sidebar [(visible)]="sidebarVisible" styleClass="sb-sidebar">\n  <!-- contenido -->\n</p-sidebar>',
    requiredInputs: [],
  },
  Breadcrumbs: {
    reactComponent: 'Breadcrumbs',
    primeNgComponent: 'Breadcrumb',
    primeNgModule: 'BreadcrumbModule',
    importPath: 'primeng/breadcrumb',
    selector: 'p-breadcrumb',
    templateExample: '<p-breadcrumb [model]="items" [home]="home" />',
    requiredInputs: ['model'],
  },
  Stepper: {
    reactComponent: 'Stepper',
    primeNgComponent: 'Steps',
    primeNgModule: 'StepsModule',
    importPath: 'primeng/steps',
    selector: 'p-steps',
    templateExample: '<p-steps [model]="steps" [(activeIndex)]="activeStep" styleClass="sb-steps" />',
    requiredInputs: ['model'],
  },
  Pagination: {
    reactComponent: 'Pagination',
    primeNgComponent: 'Paginator',
    primeNgModule: 'PaginatorModule',
    importPath: 'primeng/paginator',
    selector: 'p-paginator',
    templateExample: '<p-paginator [rows]="10" [totalRecords]="total" (onPageChange)="onPage($event)" />',
    requiredInputs: ['rows', 'totalRecords'],
  },

  // ─── Overlays / Modales ───────────────────────────────────────────────
  Dialog: {
    reactComponent: 'Dialog',
    primeNgComponent: 'Dialog',
    primeNgModule: 'DialogModule',
    importPath: 'primeng/dialog',
    selector: 'p-dialog',
    templateExample: '<p-dialog header="{{title}}" [(visible)]="visible" [modal]="true" styleClass="sb-dialog">\n  <!-- contenido -->\n</p-dialog>',
    requiredInputs: ['header'],
  },
  DialogTitle: {
    reactComponent: 'DialogTitle',
    primeNgComponent: 'Dialog',
    primeNgModule: 'DialogModule',
    importPath: 'primeng/dialog',
    selector: 'p-dialog',
    templateExample: '<!-- DialogTitle se mapea al atributo header de p-dialog -->',
    requiredInputs: [],
  },
  DialogContent: {
    reactComponent: 'DialogContent',
    primeNgComponent: 'Dialog',
    primeNgModule: 'DialogModule',
    importPath: 'primeng/dialog',
    selector: 'p-dialog',
    templateExample: '<!-- DialogContent es el contenido directo dentro de p-dialog -->',
    requiredInputs: [],
  },
  DialogActions: {
    reactComponent: 'DialogActions',
    primeNgComponent: 'Dialog',
    primeNgModule: 'DialogModule',
    importPath: 'primeng/dialog',
    selector: 'p-dialog',
    templateExample: '<ng-template pTemplate="footer">\n  <!-- botones de acción -->\n</ng-template>',
    requiredInputs: [],
  },
  Tooltip: {
    reactComponent: 'Tooltip',
    primeNgComponent: 'Tooltip',
    primeNgModule: 'TooltipModule',
    importPath: 'primeng/tooltip',
    selector: 'pTooltip',
    templateExample: '<span pTooltip="{{text}}" tooltipPosition="top">Elemento</span>',
    requiredInputs: [],
  },
  Popover: {
    reactComponent: 'Popover',
    primeNgComponent: 'OverlayPanel',
    primeNgModule: 'OverlayPanelModule',
    importPath: 'primeng/overlaypanel',
    selector: 'p-overlayPanel',
    templateExample: '<p-overlayPanel #op>\n  <!-- contenido -->\n</p-overlayPanel>\n<p-button (onClick)="op.toggle($event)" />',
    requiredInputs: [],
  },
  Menu: {
    reactComponent: 'Menu',
    primeNgComponent: 'Menu',
    primeNgModule: 'MenuModule',
    importPath: 'primeng/menu',
    selector: 'p-menu',
    templateExample: '<p-menu [model]="items" [popup]="true" #menu />\n<p-button (onClick)="menu.toggle($event)" />',
    requiredInputs: ['model'],
  },
  ConfirmDialog: {
    reactComponent: 'ConfirmDialog',
    primeNgComponent: 'ConfirmDialog',
    primeNgModule: 'ConfirmDialogModule',
    importPath: 'primeng/confirmdialog',
    selector: 'p-confirmDialog',
    templateExample: '<p-confirmDialog styleClass="sb-confirm-dialog" />',
    requiredInputs: [],
  },

  // ─── Feedback / Mensajes ──────────────────────────────────────────────
  Snackbar: {
    reactComponent: 'Snackbar',
    primeNgComponent: 'Toast',
    primeNgModule: 'ToastModule',
    importPath: 'primeng/toast',
    selector: 'p-toast',
    templateExample: '<p-toast position="bottom-right" styleClass="sb-toast" />',
    requiredInputs: [],
  },
  Alert: {
    reactComponent: 'Alert',
    primeNgComponent: 'Message',
    primeNgModule: 'MessageModule',
    importPath: 'primeng/message',
    selector: 'p-message',
    templateExample: '<p-message severity="{{severity}}" text="{{text}}" styleClass="sb-message" />',
    requiredInputs: ['severity', 'text'],
  },
  CircularProgress: {
    reactComponent: 'CircularProgress',
    primeNgComponent: 'ProgressSpinner',
    primeNgModule: 'ProgressSpinnerModule',
    importPath: 'primeng/progressspinner',
    selector: 'p-progressSpinner',
    templateExample: '<p-progressSpinner styleClass="sb-spinner" strokeWidth="4" />',
    requiredInputs: [],
  },
  LinearProgress: {
    reactComponent: 'LinearProgress',
    primeNgComponent: 'ProgressBar',
    primeNgModule: 'ProgressBarModule',
    importPath: 'primeng/progressbar',
    selector: 'p-progressBar',
    templateExample: '<p-progressBar [value]="progress" styleClass="sb-progress" />',
    requiredInputs: ['value'],
  },
  Skeleton: {
    reactComponent: 'Skeleton',
    primeNgComponent: 'Skeleton',
    primeNgModule: 'SkeletonModule',
    importPath: 'primeng/skeleton',
    selector: 'p-skeleton',
    templateExample: '<p-skeleton width="100%" height="2rem" />',
    requiredInputs: [],
  },

  // ─── File / Media ─────────────────────────────────────────────────────
  FileUpload: {
    reactComponent: 'FileUpload',
    primeNgComponent: 'FileUpload',
    primeNgModule: 'FileUploadModule',
    importPath: 'primeng/fileupload',
    selector: 'p-fileUpload',
    templateExample: '<p-fileUpload mode="advanced" [multiple]="true" accept="image/*" [maxFileSize]="1000000" />',
    requiredInputs: [],
  },
  Image: {
    reactComponent: 'Image',
    primeNgComponent: 'Image',
    primeNgModule: 'ImageModule',
    importPath: 'primeng/image',
    selector: 'p-image',
    templateExample: '<p-image [src]="url" alt="{{alt}}" [preview]="true" />',
    requiredInputs: ['src'],
  },
  Carousel: {
    reactComponent: 'Carousel',
    primeNgComponent: 'Carousel',
    primeNgModule: 'CarouselModule',
    importPath: 'primeng/carousel',
    selector: 'p-carousel',
    templateExample: '<p-carousel [value]="items" [numVisible]="3" [numScroll]="1" />',
    requiredInputs: ['value'],
  },
};
