// =============================================================================
// Central Type System for react-to-angular-mcp
// =============================================================================

// -----------------------------------------------------------------------------
// Parameter & Type Definitions (shared primitives)
// -----------------------------------------------------------------------------

export interface ParameterDefinition {
  name: string;
  type: string;
}

export interface TypeInterfaceDefinition {
  name: string;
  body: string; // TypeScript interface source code
}

// -----------------------------------------------------------------------------
// React-side IR: Extracted by AST_Parser
// -----------------------------------------------------------------------------

export interface PropDefinition {
  name: string;
  type: string; // TypeScript type annotation
  defaultValue?: string;
  isRequired: boolean;
}

export interface StateDefinition {
  variableName: string;
  setterName: string;
  type: string;
  initialValue: string;
}

export interface EffectDefinition {
  body: string; // Effect callback source
  dependencies: string[];
  cleanupFunction?: string;
}

export interface MemoDefinition {
  variableName: string;
  computeFunction: string;
  dependencies: string[];
  type: string;
}

export interface CallbackDefinition {
  functionName: string;
  body: string;
  parameters: ParameterDefinition[];
  dependencies: string[];
}

export interface RefDefinition {
  variableName: string;
  initialValue: string;
  isDomRef: boolean; // true → viewChild, false → class property
  type: string;
}

export interface ContextDefinition {
  variableName: string;
  contextName: string;
  type: string;
}

export interface CustomHookDefinition {
  hookName: string;
  serviceName: string; // Generated Angular service name
  parameters: ParameterDefinition[];
  returnType: string;
  internalHooks: string[]; // Hooks used internally
  body: string;
}

export interface MethodDefinition {
  name: string;
  parameters: ParameterDefinition[];
  returnType: string;
  body: string;
}

// -----------------------------------------------------------------------------
// JSX Tree Definitions
// -----------------------------------------------------------------------------

export interface JSXNode {
  tag: string;
  attributes: JSXAttribute[];
  children: (JSXNode | JSXExpression | string)[];
  isComponent: boolean; // true if React component (PascalCase)
}

export interface JSXAttribute {
  name: string;
  value: string | JSXExpression;
  isEventHandler: boolean;
  isDynamic: boolean;
}

export interface JSXExpression {
  type: 'conditional' | 'ternary' | 'map' | 'switch' | 'interpolation';
  expression: string;
  children?: JSXNode[];
  alternate?: JSXNode[];
}

// -----------------------------------------------------------------------------
// Security & PrimeNG Definitions
// -----------------------------------------------------------------------------

export interface PrimeNGImport {
  moduleName: string; // e.g., 'ButtonModule'
  importPath: string; // e.g., 'primeng/button'
}

export interface SecurityWarning {
  line: number;
  pattern: string;
  message: string;
  severity: 'warning' | 'error';
}

// -----------------------------------------------------------------------------
// Angular-side IR: Generated by State_Mapper
// -----------------------------------------------------------------------------

export interface SignalDefinition {
  name: string;
  type: string;
  initialValue: string;
  originalStateName: string;
}

export interface AngularEffectDefinition {
  body: string;
  dependencies: string[];
  cleanupFunction?: string;
}

export interface ComputedDefinition {
  name: string;
  type: string;
  computeFunction: string;
  dependencies: string[];
}

export interface InjectionDefinition {
  propertyName: string;
  serviceName: string;
  type: string;
}

export interface ServiceDefinition {
  serviceName: string;
  fileName: string;
  methods: AngularMethodDefinition[];
  injections: InjectionDefinition[];
}

export interface ViewChildDefinition {
  propertyName: string;
  selector: string;
  type: string;
}

export interface ClassPropertyDefinition {
  name: string;
  type: string;
  initialValue: string;
}

export interface AngularMethodDefinition {
  name: string;
  parameters: ParameterDefinition[];
  returnType: string;
  body: string;
}

// -----------------------------------------------------------------------------
// Template Binding Definitions: Generated by Template_Generator
// -----------------------------------------------------------------------------

export interface BindingDefinition {
  type: 'event' | 'property' | 'interpolation' | 'twoWay';
  angularSyntax: string;
  originalJSX: string;
}

// -----------------------------------------------------------------------------
// ComponentIR: Central Intermediate Representation
// -----------------------------------------------------------------------------

export interface ComponentIR {
  // Component metadata
  componentName: string;
  fileName: string; // kebab-case derived from componentName

  // Extracted by AST_Parser
  props: PropDefinition[];
  state: StateDefinition[];
  effects: EffectDefinition[];
  memos: MemoDefinition[];
  callbacks: CallbackDefinition[];
  refs: RefDefinition[];
  contexts: ContextDefinition[];
  customHooks: CustomHookDefinition[];
  methods: MethodDefinition[];
  childComponents: string[];
  jsxTree: JSXNode;
  typeInterfaces: TypeInterfaceDefinition[];

  // Generated by State_Mapper
  angularSignals: SignalDefinition[];
  angularEffects: AngularEffectDefinition[];
  angularComputed: ComputedDefinition[];
  angularInjections: InjectionDefinition[];
  angularServices: ServiceDefinition[];
  angularViewChildren: ViewChildDefinition[];
  classProperties: ClassPropertyDefinition[];
  componentMethods: AngularMethodDefinition[];

  // Generated by Template_Generator
  angularTemplate: string;
  isInlineTemplate: boolean; // true if < 50 lines
  templateBindings: BindingDefinition[];

  // Generated by PrimeNG_Mapper
  primeNgImports: PrimeNGImport[];
  securityWarnings: SecurityWarning[];
}

// -----------------------------------------------------------------------------
// Shell Generator Types
// -----------------------------------------------------------------------------

export interface RemoteRoute {
  name: string;
  path: string; // Route path in Angular router
  remoteEntry: string; // URL of remoteEntry.js
  exposedModule: string; // Module exposed by the remote
}

export interface ShellConfig {
  appName: string;
  remotes: RemoteRoute[];
}

export interface ShellAppArtifact {
  appConfig: string; // app.config.ts with provideRouter
  appRoutes: string; // app.routes.ts with loadRemoteModule
  federationConfig: string; // federation.config.js
  tailwindConfig: string; // tailwind.config.js (shared)
  appComponent: string; // app.component.ts with router-outlet
  cspMeta: string; // CSP configuration for index.html
}

// -----------------------------------------------------------------------------
// Module Generator Types
// -----------------------------------------------------------------------------

export interface ExposedComponent {
  name: string;
  path: string; // Relative path to the component
}

export interface ModuleConfig {
  moduleName: string;
  components: ExposedComponent[];
}

export interface GeneratedComponent {
  componentFile: string; // .component.ts content
  specFile: string; // .spec.ts content
  isPlaceholder: boolean;
}

export interface RemoteAppArtifact {
  federationConfig: string; // federation.config.js with exposes
  components: GeneratedComponent[]; // Placeholder components if they don't exist
  appConfig: string; // app.config.ts
}

// -----------------------------------------------------------------------------
// Code Emitter Types
// -----------------------------------------------------------------------------

export interface ServiceFile {
  fileName: string;
  content: string;
}

export interface AngularArtifact {
  componentFile: string; // .component.ts content
  specFile: string; // .spec.ts content
  tailwindConfig: string; // tailwind.config.js content
  templateFile?: string; // .component.html content (if not inline)
  scssFile: string; // .component.scss content
  services: ServiceFile[]; // Services generated from custom hooks
  securityWarnings: SecurityWarning[];
}

// -----------------------------------------------------------------------------
// Validation Types
// -----------------------------------------------------------------------------

export interface ValidationError {
  type: 'syntax' | 'security' | 'size' | 'timeout' | 'invalid_component';
  message: string;
  line?: number;
  column?: number;
}

export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  warnings: SecurityWarning[];
  sanitizedCode?: string; // Clean code if valid
}
