INSERT INTO errores (intento_id, code, message, category, mcp_layer) VALUES
(7, 'NG9', 'Property stats does not exist on AppComponent', 'missing_property', 'code-emitter'),
(7, 'NG8002', 'Cant bind to services - not known property of app-service-list', 'binding', 'signal-fixer'),
(7, 'NG8001', 'p-toast is not a known element', 'primeng_import', 'primeng-mapper'),
(7, 'TS2304', 'Cannot find name saveService', 'missing_name', 'code-emitter'),
(7, 'NG8', 'WritableSignal unknown must have Symbol.iterator', 'signal_type', 'code-emitter'),
(7, 'NG9', 'Property src does not exist on EvidenceUploadComponent', 'missing_property', 'template-generator'),
(7, 'NG9', 'Property index does not exist on EvidenceUploadComponent', 'missing_property', 'template-generator'),
(7, 'NG5', 'Operator < cannot be applied to number and WritableSignal unknown', 'signal_type', 'code-emitter'),
(7, 'NG9', 'Property current does not exist on Signal ElementRef', 'missing_property', 'code-emitter'),
(7, 'TS2571', 'Object is of type unknown', 'signal_type', 'code-emitter'),
(7, 'TS2663', 'Cannot find name onChange. Did you mean this.onChange?', 'this_scope', 'class-context-layer'),
(7, 'TS2663', 'Cannot find name evidencias. Did you mean this.evidencias?', 'this_scope', 'class-context-layer'),
(7, 'TS2663', 'Cannot find name fallido. Did you mean this.fallido?', 'this_scope', 'class-context-layer'),
(7, 'TS2663', 'Cannot find name tuvoNovedades. Did you mean this.tuvoNovedades?', 'this_scope', 'class-context-layer'),
(7, 'TS2663', 'Cannot find name onSuccess. Did you mean this.onSuccess?', 'this_scope', 'class-context-layer'),
(7, 'NG8001', 'p-card is not a known element', 'primeng_import', 'primeng-mapper'),
(7, 'NG8001', 'p-select is not a known element', 'primeng_import', 'primeng-mapper'),
(7, 'NG8001', 'p-tag is not a known element', 'primeng_import', 'primeng-mapper'),
(7, 'NG8002', 'Cant bind to options - not known property of p-select', 'binding', 'primeng-mapper'),
(7, 'NG8002', 'Cant bind to evidencias - not known property of app-evidence-upload', 'binding', 'signal-fixer'),
(7, 'NG8002', 'Cant bind to variant - not known property of p-tag', 'binding', 'template-generator'),
(7, 'NG5002', 'Parser Error format new Date in template', 'template_parse', 'template-generator'),
(7, 'NG1', 'Property service does not exist on ServiceListComponent. Did you mean services?', 'missing_property', 'template-generator'),
(7, 'TS2304', 'Cannot find name ServiceType', 'missing_name', 'code-emitter'),
(7, 'TS2306', 'File types.ts is not a module', 'import_path', 'code-emitter'),
(7, 'TS1005', 'Semicolon expected in service', 'syntax', 'code-emitter'),
(7, 'TS7006', 'Parameter implicitly has any type', 'type_safety', 'code-emitter'),
(7, 'TS7030', 'Not all code paths return a value', 'type_safety', 'code-emitter');
